# Generated by Django 3.2 on 2025-11-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request_name', models.CharField(max_length=128, verbose_name='Название')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MERGED', 'Merged')], max_length=6, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('merged_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время слияния')),
                ('assigned_reviewers', models.ManyToManyField(blank=True, related_name='review_assignments', to='users.User', verbose_name='Ревьюверы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.user', verbose_name='Автор')),
            ],
        ),
    ]
